neo4j:
  # Database connection settings
  uri: "bolt://localhost:7687"  # Neo4j database URI
  username: "neo4j"            # Database username
  password: "your_password"    # Database password
  
  # Database configuration
  database: "tikg"            # Database name
  encrypted: false            # Whether to use encrypted connection
  
  # Connection pool settings
  max_connection_lifetime: 3600  # Maximum connection lifetime in seconds
  max_connection_pool_size: 50   # Maximum number of connections in the pool
  connection_timeout: 30         # Connection timeout in seconds
  
  # Graph configuration
  node_labels:
    - "ThreatActor"
    - "Malware"
    - "Tactic"
    - "Technique"
    - "Tool"
    - "Vulnerability"
    - "Infrastructure"
    - "Campaign"
    
  relationship_types:
    - "USES"
    - "TARGETS"
    - "BELONGS_TO"
    - "INDICATES"
    - "EXPLOITS"
    - "PART_OF"
    - "SIMILAR_TO"
    - "RELATED_TO"
    
  # Index configuration
  indexes:
    - name: "threat_actor_name"
      type: "BTREE"
      labels: ["ThreatActor"]
      properties: ["name"]
      
    - name: "malware_name"
      type: "BTREE"
      labels: ["Malware"]
      properties: ["name"]
      
    - name: "technique_id"
      type: "BTREE"
      labels: ["Technique"]
      properties: ["mitre_id"]
      
    - name: "vulnerability_cve"
      type: "BTREE"
      labels: ["Vulnerability"]
      properties: ["cve_id"] 